on: [push, pull_request]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-only-ios:
    name: Build only (iOS)
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET Workloads
        run: dotnet workload install ios

      # https://github.com/dotnet/macios/issues/19157
      # https://github.com/actions/runner-images/issues/12758
      - name: Use Xcode 16.4
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Build
        run: dotnet build -c Debug osu.iOS.slnf
